In [ ]:
import pandas as pd

data = {'Full_Name': ['John Smith', 'Jane Doe', 'Peter Jones-Smith', 'Mary', 'Juan de la Cruz']}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
           Full_Name
0         John Smith
1           Jane Doe
2  Peter Jones-Smith
3               Mary
4    Juan de la Cruz

In [19]:
hitters_file = pd.read_csv('hitter_stats_metrics.csv')
hitters_file[['last_name', 'first_name']] = hitters_file['last_name, first_name'].str.split(',', n=1, expand=True)
hitters_file.drop(columns=['last_name, first_name'], inplace=True)
hitters_file.columns = hitters_file.columns.str.replace('_',' ')
hitters_file.head()

,player id,year,player age,ab,pa,hit,single,double,triple,home run,...,meatball swing percent,iz contact percent,in zone percent,whiff percent,pull percent,straightaway percent,opposite percent,sprint speed,last name,first name
0,112526,2015,42,58,64,8,7,1,0,0,...,70.6,79.2,66.1,30.6,20.5,48.7,30.8,20.2,Colon,Bartolo
1,120074,2015,39,528,614,144,70,37,0,37,...,76.8,83.0,41.2,23.2,41.9,36.4,21.7,23.1,Ortiz,David
2,407793,2015,36,62,70,7,5,2,0,0,...,39.1,79.2,54.3,30.1,19.0,33.3,47.6,21.1,Lackey,John
3,407812,2015,35,229,277,64,43,16,1,4,...,82.3,83.4,42.4,22.5,22.4,44.3,32.8,26.0,Holliday,Matt
4,408236,2015,33,571,642,157,96,33,0,28,...,83.1,85.4,42.3,21.6,37.0,34.7,28.3,24.0,González,Adrián

In [20]:
hitters_file.to_csv('cleaned_hitter_stats_metrics.csv', index=False)

In [16]:
pitchers_file = pd.read_csv('pitcher_stats_metrics.csv')
pitchers_file[['last_name', 'first_name']] = pitchers_file['last_name, first_name'].str.split(',', n=1, expand=True)
pitchers_file.drop(columns=['last_name, first_name'], inplace=True)
pitchers_file.head()

,player_id,year,player_age,p_game,p_formatted_ip,strikeout,walk,k_percent,bb_percent,batting_avg,...,in_zone_percent,whiff_percent,swing_percent,f_strike_percent,groundballs_percent,flyballs_percent,linedrives_percent,popups_percent,last_name,first_name
0,112526,2015,42,33,194.2,136,24,16.7,2.9,0.281,...,54.3,14.7,48.6,66.6,44.1,23.2,27.0,5.7,Colon,Bartolo
1,115629,2015,42,42,38.2,34,7,21.0,4.3,0.286,...,54.7,17.3,51.9,60.5,55.4,18.2,20.7,5.8,Hawkins,LaTroy
2,150116,2015,38,8,34.2,28,15,17.4,9.3,0.319,...,45.1,16.2,46.5,54.0,46.2,17.9,30.8,5.1,Wolf,Randy
3,150302,2015,36,9,47.1,37,14,17.1,6.5,0.330,...,43.3,21.6,46.1,54.2,48.8,17.1,30.5,3.7,Marquis,Jason
4,150359,2015,38,26,164.0,143,49,20.5,7.0,0.275,...,48.2,22.3,45.1,60.8,55.0,14.1,26.8,4.0,Burnett,A.J.

In [17]:
pitchers_file.to_csv('cleaned_pitcher_stats_metrics.csv', index=False)